name: Coverage Report

on:
  workflow_run:
    workflows: ["CI_Main"]
    branches: [main]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 2e7e3f36cd48b7af73ff23ddba53efef4bc7a985fb84f67db74ab95cdfbebaa1
        with:
          coverageCommand: npm run coverage
